### ISSUE TITLE
[dexter-cli_0.10.5] Analysis result is not sent to server

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#118]
Analysis is performed and defects are found, however defects from are not sent to server. 
On version 0.10.2 with the same configuration, it works correctly. 

Config file: [dexter_cfg.json.txt](https://github.com/Samsung/Dexter/files/500370/dexter_cfg.json.txt)

Log file: [dexter-executor.log.txt](https://github.com/Samsung/Dexter/files/500380/dexter-executor.log.txt)

**Comment by Minjung-Baek** [comment]
We decided to add Default 'Admin' account for account management, again.
