### ISSUE TITLE
[dexter-vs] Doesn't scan solution files.

### ISSUE THREAD

**Issue by DianaNites** [Samsung/Dexter#171]
The visual studio plugin will under no circumstances scan any file part of a solution. It will only scan files in the same directory or subdirectory as the solution, with no regard to if they're part of the solution or not, or any files outside the solution directory(Such as the case with CMake generated solutions.)

**Comment by KarolAntczak** [comment]
Thanks for noticing! You're right. 
I will check if VS API allows to list all files in solution regardless of their actual location. If so, I will provide a fix soon.

Regars
Karol

**Comment by iaz3** [comment]
Thanks, good luck. I did some googling of my own and it seems it's less than fun to do.

This stackoverflow may be helpful https://stackoverflow.com/questions/1434720/get-a-list-of-solution-project-files-for-vs-add-in-or-dxcore-plugin
