### ISSUE TITLE
UnitTests failing (5 of 22) while building in linux environment

### ISSUE THREAD

**Issue by t-tomaszewicz** [Samsung/Dexter#175]
root@wawsrvkloclin04:~/project# gradle build
...
17 tests completed, 5 failed
:dexter-metrics:test FAILED
...
Environment:
root@wawsrvkloclin04:# uname -ra
Linux wawsrvkloclin04 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@wawsrvkloclin04:# java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-3)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

[DexterUnitTestResult.zip](https://github.com/Samsung/Dexter/files/1747541/DexterUnitTestResult.zip)

**Comment by KarolAntczak** [comment]
Tests under Linux are now passing.
