### ISSUE TITLE
[dexter-monitor 0.9.2] Email is not sent when server is down

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#42]
When dexter-server instance is down, dexter-monitor should sent an email to server administrator. But the email is not sent. 

Here is my server-list.json:

```
{
    {
        "type": "Dexter Server",
        "group": "SE",
        "name": "Test server",
        "heartbeat": "http://123.123.123.10:4982/api/v1/isServerAlive",
        "heartbeatInDetail":"http://123.123.123.10:4982/api/v2/server-detailed-status",
        "emailingWhenServerDead": true,
        "emailList": ["k.antczak@samsung.com" ],
        "serverAdministrator": "Admin name"
    }
}
```

**Comment by Min-Ho-Kim** [comment]
Hi,
Did you set the email configuration in the config.json file under the dexter-monitor folder?
You can make your own email API server or use SMTP like a gmail.
However, I don't recommend that you use SMTP which is not in-house.

Anyway, if you want to use HQ email server that we made I can open it for you for Dexter purpose.
Please let me know about this by the company email : min.ho.kim@samsung.com
