### ISSUE TITLE
User Guide for Dexter Server and Clients (WIKI and PDF)

### ISSUE THREAD

**Issue by Min-Ho-Kim** [Samsung/Dexter#7]
WIKI : https://dexter.atlassian.net
PDF: github 'doc' folder

Contents :  how to install  and use
- [ ] Dexter Server
- [ ] Dexter Eclipse
- [ ] Dexter Source Insight
- [ ] Dexter CLI
- [ ] Dexter WEB (Defect List, Dashboard)

**Comment by Minjung-Baek** [comment]
https://dexter.atlassian.net/wiki/display/DW/Dexter+Wiki
