### ISSUE TITLE
[dexter-monitor] Empty data displayed, when at least one dexter-server is busy

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#94]
When one of dexter-server instances is busy (it is performing analysis), dexter-monitor displays 0s instead of correct numbers:

![image](https://cloud.githubusercontent.com/assets/13940703/18240087/d6775b98-7349-11e6-87ba-491a23c1644d.png)

**Comment by marchpig** [comment]
It may need some timout handling code for busy servers.

**Comment by marchpig** [comment]
Fixed this issue : https://github.com/Samsung/Dexter/pull/95
